{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "building 615 floor 2",
   "type": "canvas",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cucumber\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"f199a2094793\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "building 615 floor 3",
   "type": "canvas",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  { "title": "map", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  { "title": "Location 15316", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Sensor10",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cucumber\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"light\" or r[\"_field\"] == \"hum\" or r[\"_field\"] == \"temp\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"f199a2094793\")\r\n  |> filter(fn: (r) => r[\"sensor_id\"] == \"60:55:F9:ED:36:E8\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"cucumber/sensors/60:55:F9:ED:36:E8\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Sensor09",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cucumber\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hum\" or r[\"_field\"] == \"light\" or r[\"_field\"] == \"temp\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"f199a2094793\")\r\n  |> filter(fn: (r) => r[\"sensor_id\"] == \"60:55:F9:EC:D4:4E\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"cucumber/sensors/60:55:F9:EC:D4:4E\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Location 15315", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Sensor8",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cucumber\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hum\" or r[\"_field\"] == \"light\" or r[\"_field\"] == \"temp\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"f199a2094793\")\r\n  |> filter(fn: (r) => r[\"sensor_id\"] == \"60:55:F9:ED:36:E8\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"cucumber/sensors/60:55:F9:ED:36:E8\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Location 15301", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Sensor07",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cucumber\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hum\" or r[\"_field\"] == \"light\" or r[\"_field\"] == \"temp\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"f199a2094793\")\r\n  |> filter(fn: (r) => r[\"sensor_id\"] == \"60:55:F9:EC:C3:D6\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"cucumber/sensors/60:55:F9:EC:C3:D6\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Sensor6",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cucumber\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hum\" or r[\"_field\"] == \"light\" or r[\"_field\"] == \"temp\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"f199a2094793\")\r\n  |> filter(fn: (r) => r[\"sensor_id\"] == \"60:55:F9:EC:D4:4E\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"cucumber/sensors/60:55:F9:EC:D4:4E\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Location 15213", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Sensor05",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 111 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cucumber\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hum\" or r[\"_field\"] == \"light\" or r[\"_field\"] == \"temp\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"f199a2094793\")\r\n  |> filter(fn: (r) => r[\"sensor_id\"] == \"7C:DF:A1:00:AA:66\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"cucumber/sensors/7C:DF:A1:00:AA:66\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Sensor04",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cucumber\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"light\" or r[\"_field\"] == \"temp\" or r[\"_field\"] == \"hum\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"f199a2094793\")\r\n  |> filter(fn: (r) => r[\"sensor_id\"] == \"68:67:25:2D:02:6E\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"cucumber/sensors/68:67:25:2D:02:6E\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Sensor03",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 128 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cucumber\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hum\" or r[\"_field\"] == \"light\" or r[\"_field\"] == \"temp\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"f199a2094793\")\r\n  |> filter(fn: (r) => r[\"sensor_id\"] == \"60:55:F9:ED:22:2C\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"cucumber/sensors/60:55:F9:ED:22:2C\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Sensor02",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 136 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cucumber\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hum\" or r[\"_field\"] == \"temp\" or r[\"_field\"] == \"light\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"f199a2094793\")\r\n  |> filter(fn: (r) => r[\"sensor_id\"] == \"60:55:F9:ED:8D:EA\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"cucumber/sensors/60:55:F9:ED:8D:EA\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Sensor01",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 145 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cucumber\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hum\" or r[\"_field\"] == \"temp\" or r[\"_field\"] == \"light\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"f199a2094793\")\r\n  |> filter(fn: (r) => r[\"sensor_id\"] == \"60:55:F9:ED:92:00\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"cucumber/sensors/60:55:F9:ED:92:00\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}